---
title: "Our Story"
output:
  html_document:
    fig_width: 1
---

We are marine scientists, and we are using open data science tools to understand ocean health <!--- tackle  science///FOR A BETTER FUTURE.. --->

Science-based decision-making to protect the environment relies on collaborating with scientists across social and scientific disciplines, and developing transparent science the public can understand and trust. It is also time-sensitive given the rapidly changing environment. We as scientists have the responsibility and opportunity to make our science transparent, reproducible, and well communicated. Only in this way we can effectively assist policy makers make decisions based on the best science available. 

For the past five years, at the Ocean Health Index, our team have improved the way we do science by embracing data science and open science, and made OHI toolbox accessible to more than 20 countries around the world, who are able to build off our science and code to assess their ocean health. 

We're sharing our story because we were intimidated at the time and expertise involved to learn these tools, but we are living proof that it's possible, and that it will improve your science and make it accessible and usable for management. This is the future of environmental science.



<!---TODO JULIE--->
- Linked to published paper.
- Github link <!---TODO JULIE--->
- Q&A
- Press
- Blog

<!---TODO NING--->
- Fig 1

- MEAM webinar: telling our story to a wider audience
